### ISSUE TITLE
STA437

### ISSUE THREAD

**Issue by George9897** [UT-Applicataion-Development-Association/course-wiki#51]
# 文章信息
title: STA437

subtitle: Methods of Multivariate Data

author: George

tags:
  - UTSG
  
  - Department of Statistics
  

## 课程介绍
主要属于统计里面的数学，不需要会coding, 偏重matrix的知识。对于223/224的要求比较多，会有些小证明和matrix的运算需要熟练。

统计中用到matrix的地方很多，这节课从一开始就使用大量的matrix形式或者vector形式进行运算，不再像300 或300以下level的统计课大多都还使用scalor来作为变量， 而是对整个dataset或者向量做运算。

证明更类似于MAT223的证明，大多是简单的Show，过程不需要很严谨的格式，该有的点具备了就可以了。

## 大体课设
80% 1 hr quiz (5 * 16%)
20% Final exam

## 常驻教授
Medhi Molkaraie (Fall 2020和Winter2021都是他教)

## 课程难度
由于Online的原因，课程变成5个quiz加一个final了。 quiz 相对比较简单，毕竟只有一个小时，每次两到三大题，给分也挺松。占80%导致这节课上80+ 挺容易的， final 随考考能上A

- 内容难度:  3.5/ 5

- 作业难度:  3/ 5

- Workload:  3/ 5

- Overall难度:  3/ 5

**Comment by dinolii** [comment]
Merge with existing post
