### ISSUE TITLE
COG260

### ISSUE THREAD

**Issue by George9897** [UT-Applicataion-Development-Association/course-wiki#52]
# 文章信息
title: COG260

subtitle: Data, Computation, and The Mind

author: George

tags:
  - UTSG
  
  - Cognitive Science
  

## 课程介绍
一节刚开了不久的小班化的大二的涉及浅显的Data Science的新课。通常大二的课程都有至少100+的课位量，但这节课只offer Fall semester,并且只有40个的课位，毕竟还不是online的时候是在BA的lab里授课的。

这节课的教授每年都为Yang Xu, 一位跨CS于Cog Sci Department的一位研究生导师。 教授讲课清晰，内容还算有趣，主要给分真的挺松的。10% 的Participation mark基本上是白送的，只要坐在教室里就可以了。

这节课的6个lab，每个都基本会是当周的topic，使用python 语言完成，可以组队可以solo，教授会在每周lecture中留出一小时时间给大家开始做lab以及现场答疑。在开学后的前6周里，前几个lab很容易上手，基本课上一小时就能完成，后几个也是完全能在给的一周的时间内轻松完成的。

Project占这节课的后半部分，教授会指定几个topic以及数据库，也可以自己找来完成这个project. Project也可以两个人一组，project要求不算严格，且每一个部分只要花点时间做了，几乎不会扣很多分。

## 大体课设
（2018 Fall）
- 10% Participation (基本上只要去了就给分)
- 60% Lab （6 * 10 %）
- 5% Project proposal  
- 10% Project presentation
- 15% Project report
- * Project 为两个人一组

## 常驻教授
Yang Xu

## 课程难度
没有任何形式的考试，教授给分松，作业可以组队，算是一门比较轻松的课

- 内容难度: 3.5 / 5

- 作业难度:  3.5/ 5

- Workload: 3 / 5

- Overall难度:  3.5/ 5

**Comment by dinolii** [comment]
Add to posts
